import Foundation
#if os(iOS)
import UIKit
#endif

struct SubjectStat: Identifiable {
    let id = UUID()
    let subject: String
    let completed: Int
    let total: Int

    var fraction: Double {
        guard total > 0 else { return 0 }
        return Double(completed) / Double(total)
    }

    var percent: Int { Int(fraction * 100) }
}

struct ReportSnapshot {
    let studentName: String
    let completedCount: Int
    let totalCount: Int
    let badgeCount: Int
    let subjectStats: [SubjectStat]
    let generatedAt: Date
}

final class PDFExportService {

    static func generateReport(_ snapshot: ReportSnapshot) -> URL? {
        #if os(iOS)
        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)
        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            draw(snapshot: snapshot, in: pageRect)
        }
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("\(snapshot.studentName)_EduAssist_Report.pdf")
        try? data.write(to: url)
        return url
        #else
        return nil
        #endif
    }

    #if os(iOS)
    private static func draw(snapshot: ReportSnapshot, in page: CGRect) {
        let margin: CGFloat = 50
        var y: CGFloat = margin

        let titleFont   = UIFont.boldSystemFont(ofSize: 22)
        let headFont    = UIFont.boldSystemFont(ofSize: 14)
        let bodyFont    = UIFont.systemFont(ofSize: 13)
        let smallFont   = UIFont.systemFont(ofSize: 10)
        let black       = UIColor.black
        let gray        = UIColor.darkGray
        let light       = UIColor.lightGray

        func attr(_ font: UIFont, _ color: UIColor) -> [NSAttributedString.Key: Any] {
            [.font: font, .foregroundColor: color]
        }

        // ── Header ──────────────────────────────────────────────────────────
        "EduAssist Progress Report".draw(at: CGPoint(x: margin, y: y), withAttributes: attr(titleFont, black))
        y += 34

        "Student: \(snapshot.studentName)".draw(at: CGPoint(x: margin, y: y), withAttributes: attr(bodyFont, gray))
        y += 20
        "Generated: \(snapshot.generatedAt.formatted(date: .long, time: .omitted))".draw(
            at: CGPoint(x: margin, y: y), withAttributes: attr(bodyFont, gray))
        y += 28

        // divider
        let divider = UIBezierPath()
        divider.move(to: CGPoint(x: margin, y: y))
        divider.addLine(to: CGPoint(x: page.width - margin, y: y))
        light.setStroke()
        divider.stroke()
        y += 20

        // ── Overall Progress ─────────────────────────────────────────────────
        "Overall Progress".draw(at: CGPoint(x: margin, y: y), withAttributes: attr(headFont, black))
        y += 22

        let pct = snapshot.totalCount > 0
            ? Int(Double(snapshot.completedCount) / Double(snapshot.totalCount) * 100) : 0
        [
            "Lessons Completed: \(snapshot.completedCount) of \(snapshot.totalCount)",
            "Completion Rate:    \(pct)%",
            "Badges Earned:      \(snapshot.badgeCount)"
        ].forEach {
            $0.draw(at: CGPoint(x: margin + 12, y: y), withAttributes: attr(bodyFont, gray))
            y += 20
        }
        y += 16

        // ── Subject Breakdown ────────────────────────────────────────────────
        if !snapshot.subjectStats.isEmpty {
            "Subject Breakdown".draw(at: CGPoint(x: margin, y: y), withAttributes: attr(headFont, black))
            y += 22

            for stat in snapshot.subjectStats {
                guard y < page.height - margin - 20 else { break }
                let line = "\(stat.subject): \(stat.completed)/\(stat.total)  (\(stat.percent)%)"
                line.draw(at: CGPoint(x: margin + 12, y: y), withAttributes: attr(bodyFont, gray))
                y += 20
            }
        }

        // ── Footer ───────────────────────────────────────────────────────────
        "Generated by EduAssist  ·  Confidential".draw(
            at: CGPoint(x: margin, y: page.height - margin),
            withAttributes: attr(smallFont, light))
    }
    #endif
}
