import Foundation

// Phase 1: Educational tips for loading screens
struct EducationalTips {
    static let tips = [
        "Did you know? The human brain can process images 60,000 times faster than text!",
        "Tip: Taking short breaks every 20 minutes helps your brain retain information better.",
        "Fun fact: Honey never spoils. Archaeologists found 3000-year-old honey in Egyptian tombs!",
        "Learning tip: Teaching someone else what you've learned helps you remember it 90% better.",
        "Did you know? Octopuses have three hearts and blue blood!",
        "Study tip: The Pomodoro Technique: 25 minutes of focus, then a 5-minute break.",
        "Fun fact: A day on Venus is longer than a year on Venus!",
        "Memory tip: Associate new information with things you already know to remember it better.",
        "Did you know? The shortest war in history lasted only 38 minutes!",
        "Learning tip: Get enough sleep - your brain consolidates memories while you rest.",
        "Fun fact: Bananas are berries, but strawberries aren't!",
        "Study tip: Use flashcards for active recall - one of the most effective learning methods.",
        "Did you know? The Eiffel Tower can grow by 6 inches in summer due to heat expansion!",
        "Focus tip: Remove distractions by putting your phone in another room while studying.",
        "Fun fact: A group of flamingos is called a 'flamboyance'!",
        "Learning tip: Practice problems are more effective than re-reading textbook chapters.",
        "Did you know? The human nose can detect over 1 trillion different scents!",
        "Memory tip: Create a story or mnemonic to remember lists of information.",
        "Fun fact: Cows have best friends and get stressed when separated!",
        "Study tip: Space out your learning over time instead of cramming - it's more effective.",
        "Did you know? The Great Wall of China isn't visible from space with the naked eye!",
        "Focus tip: Set specific goals for each study session to stay on track.",
        "Fun fact: Sloths can hold their breath longer than dolphins (up to 40 minutes)!",
        "Learning tip: Ask questions - curiosity helps your brain make new connections.",
        "Did you know? The first oranges weren't orange - they were green!",
        "Memory tip: Review material within 24 hours to move it from short-term to long-term memory.",
        "Fun fact: A cloud can weigh more than a million pounds!",
        "Study tip: Use different colors for notes to organize information visually.",
        "Did you know? The human eye can distinguish about 10 million different colors!",
        "Focus tip: Stay hydrated - your brain needs water to function at its best.",
        "Fun fact: Wombat poop is cube-shaped!",
        "Learning tip: Connect new concepts to real-world examples for better understanding.",
        "Did you know? The first computer bug was an actual bug - a moth caught in a relay!",
        "Memory tip: Use the method of loci - associate information with familiar places.",
        "Fun fact: Sea otters hold hands while sleeping so they don't drift apart!",
        "Study tip: Teach the material to an imaginary student to test your understanding.",
        "Did you know? The shortest complete sentence in English is 'I am.'!",
        "Focus tip: Create a dedicated study space to train your brain to focus there.",
        "Fun fact: A shrimp's heart is in its head!",
        "Learning tip: Don't just memorize - understand the 'why' behind concepts.",
        "Did you know? The first alarm clock could only ring at 4 AM!",
        "Memory tip: Use spaced repetition - review material at increasing intervals.",
        "Fun fact: Kangaroos can't walk backwards!",
        "Study tip: Summarize information in your own words to check comprehension.",
        "Did you know? The first video ever uploaded to YouTube was 'Me at the zoo'!",
        "Focus tip: Break large tasks into smaller, manageable chunks.",
        "Fun fact: A jellyfish is 95% water!",
        "Learning tip: Use analogies to explain complex ideas simply.",
        "Did you know? The first product with a bar code was a pack of Wrigley's gum!",
        "Memory tip: Create mind maps to visualize connections between ideas.",
        "Fun fact: Cows have four stomachs!",
        "Study tip: Practice active recall by testing yourself without looking at notes.",
        "Did you know? The first email was sent in 1971 by Ray Tomlinson to himself!",
        "Focus tip: Use the 2-minute rule - if something takes less than 2 minutes, do it now!",
        "Fun fact: A snail can sleep for 3 years!",
        "Learning tip: Don't be afraid to make mistakes - they're part of the learning process.",
        "Did you know? The first domain name ever registered was symbolics.com!",
        "Memory tip: Use chunking - break information into smaller groups to remember better.",
        "Fun fact: A group of porcupines is called a 'prickle'!",
        "Study tip: Vary your study methods to keep your brain engaged.",
        "Did you know? The first emoji was created in 1999 in Japan!",
        "Focus tip: Use background music without lyrics to improve concentration.",
        "Fun fact: The moon has moonquakes!",
        "Learning tip: Set specific, measurable, achievable, relevant, and time-bound (SMART) goals.",
        "Did you know? The first text message was sent in 1992 and said 'Merry Christmas'!",
        "Memory tip: Use the Feynman Technique - explain concepts in simple terms.",
        "Fun fact: A bolt of lightning contains enough energy to toast 100,000 slices of bread!",
        "Study tip: Review your mistakes to understand what went wrong and how to improve.",
        "Did you know? The first website is still online at info.cern.ch!",
        "Focus tip: Use time-blocking to dedicate specific hours to specific subjects.",
        "Fun fact: The human brain uses 20% of the body's total energy!",
        "Learning tip: Connect new learning to your personal interests and experiences.",
        "Did you know? The first video game was created in 1958 and was called 'Tennis for Two'!",
        "Memory tip: Use visualization - create mental images of what you're learning.",
        "Fun fact: A cloud can weigh more than a million pounds!",
        "Study tip: Take handwritten notes - they help with retention better than typing.",
        "Did you know? The first smartphone was invented in 1992, 15 years before the iPhone!",
        "Focus tip: Use the Eisenhower Matrix to prioritize tasks by urgency and importance.",
        "Fun fact: The human heart beats about 100,000 times a day!",
        "Learning tip: Stay curious - ask 'why' and 'how' questions about everything.",
        "Did you know? The first 3D movie was shown in 1922!",
        "Memory tip: Use acronyms to remember lists of items.",
        "Fun fact: A day on Mars is about 24 hours and 37 minutes!",
        "Study tip: Find a study buddy to discuss concepts and quiz each other.",
        "Did you know? The first artificial satellite, Sputnik, was the size of a beach ball!",
        "Focus tip: Use the 80/20 rule - focus on the 20% of material that gives 80% of results.",
        "Fun fact: The human tongue has over 10,000 taste buds!",
        "Learning tip: Don't multitask - focus on one thing at a time for better results.",
        "Did you know? The first computer mouse was made of wood!",
        "Memory tip: Use storytelling to remember sequences of information.",
        "Fun fact: A group of crows is called a 'murder'!",
        "Study tip: Review material right before sleep for better retention.",
        "Did you know? The first digital camera was invented in 1975 by Kodak!",
        "Focus tip: Use positive self-talk to boost confidence and motivation.",
        "Fun fact: The human skeleton is completely replaced every 10 years!",
        "Learning tip: Celebrate small wins to stay motivated on your learning journey."
    ]
    
    static func randomTip() -> String {
        tips.randomElement() ?? "Keep learning and growing every day!"
    }
}
